#!/usr/bin/env bash

set -o nounset
set -o errexit
set -o pipefail
set -x

BASE_COLLECTION_PATH="${BASE_COLLECTION_PATH:-/must-gather}"
GPU_OPERATOR_COLLECTION_PATH="$BASE_COLLECTION_PATH/nvidia-gpu-operator"

mkdir -p "$GPU_OPERATOR_COLLECTION_PATH"

OPERATOR_IMAGE=$(oc get pods -A -lapp=gpu-operator -o=jsonpath='{.items[0].spec.containers[0].image}' 2> /dev/null)
oc adm must-gather --image="$OPERATOR_IMAGE" --dest-dir="$GPU_OPERATOR_COLLECTION_PATH" &> /dev/null

sync